[project]
name = "cltv-insurance"
version = "0.1.0"
description = "Machine learning predictive modeling for motor insurance Customer Lifetime Value (CLTV) using LightGBM and XGBoost"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "ipykernel>=7.4.0",
    "lightbgm",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]
